### ISSUE TITLE
Kernel 6.3 fix

### ISSUE THREAD

**Issue by dmanlfc** [lwfinger/rtl8723du#39]
```
diff --git a/os_dep/ioctl_cfg80211.c b/os_dep/ioctl_cfg80211.c
index 64541a3641..a2d9d49fcf 100644
--- a/os_dep/ioctl_cfg80211.c
+++ b/os_dep/ioctl_cfg80211.c
@@ -173,6 +173,8 @@ u8 rtw_cfg80211_ch_switch_notify(struct adapter *adapter, u8 ch, u8 bw, u8 offse
 
 #if LINUX_VERSION_CODE < KERNEL_VERSION(5, 19, 2)
 	cfg80211_ch_switch_notify(adapter->pnetdev, &chdef);
+#elif (LINUX_VERSION_CODE >= KERNEL_VERSION(6, 3, 0))
+	cfg80211_ch_switch_notify(adapter->pnetdev, &chdef, 0, 0);
 #else
 	cfg80211_ch_switch_notify(adapter->pnetdev, &chdef, 0);
 #endif
```

or use the driver in linux 6.2+ with 

```
CONFIG_RTW88
CONFIG_RTW88_8723DU
CONFIG_WLAN
CONFIG_WLAN_VENDOR_REALTEK
```

**Comment by lwfinger** [comment]
Thanks. I also recommend using the rtw88 driver, either the built-in version in 6.2+, or the later version in https://github.com/lwfinger/rtw88.git.

BTW, I will soo drop maintenance of this repo.

**Comment by dmanlfc** [comment]
still useful for older kernel arm systems @lwfinger - thanks for providing it

**Comment by lwfinger** [comment]
OK, I will keep it for now. How old a kernel are you describing?

**Comment by dmanlfc** [comment]
Some SBC's go back to 4.4 but most are now going to 6.1LTS
What is the minimum kernel version for this driver?

**Comment by lwfinger** [comment]
It certainly builds on 6.1. I do not know about the 4.4. I cannot even do a test of a kernel that old. My gcc version would croak!

**Comment by geekycow** [comment]
I normally have it working via dkms but it's failing to compile for Ubuntu 22.04.2 LTS on kernel version 5.19.0-42-generic (it worked for 5.19.0-38-generic) which I'm suspecting might relate to this same kernel version based if-else?  Apologies if not.

Doing a refresh git clone and manual compile as per the readme it fails with this-

```  CC [M]  /home/julie/tmp/rtl8723du/os_dep/linux/ioctl_cfg80211.o
/home/julie/tmp/rtl8723du/os_dep/linux/ioctl_cfg80211.c: In function ‘rtw_wdev_unregister’:
/home/julie/tmp/rtl8723du/os_dep/linux/ioctl_cfg80211.c:10623:17: error: ‘struct wireless_dev’ has no member named ‘current_bss’
10623 |         if (wdev->current_bss) {
      |                 ^
```
