### ISSUE TITLE
ioctl_cfg80211.c:458:3: error: too many arguments to function ‘cfg80211_ch_switch_started_notify’ [SOLVED]

### ISSUE THREAD

**Issue by Vadimatorik** [lwfinger/rtl8723du#40]
Hi!)
My laptop: DEXP Aquilon
My OS: Ubuntu 20.04.6 LTS
My core version: 5.15.0-72-generic
A try to build code from this repository (branch v5.13.4).
I installed all requirements,
A see this message:
```
$ make
Makefile:2541: warning: overriding recipe for target 'sign'
Makefile:2476: warning: ignoring old recipe for target 'sign'
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.15.0-72-generic/build M=/home/vadimatorik/Downloads/rtl8723du  modules
make[1]: Entering directory '/usr/src/linux-headers-5.15.0-72-generic'
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/rtw_cmd.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/rtw_security.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/rtw_debug.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/rtw_io.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/rtw_ioctl_query.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/rtw_ioctl_set.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/rtw_ieee80211.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/rtw_mlme.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/rtw_mlme_ext.o
/home/vadimatorik/Downloads/rtl8723du/core/rtw_mlme_ext.c: In function ‘rtw_txpwr_init_regd’:
/home/vadimatorik/Downloads/rtl8723du/core/rtw_mlme_ext.c:304:6: warning: this statement may fall through [-Wimplicit-fallthrough=]
  304 |   if (rfctl->txpwr_lmt_name)
      |      ^
/home/vadimatorik/Downloads/rtl8723du/core/rtw_mlme_ext.c:307:2: note: here
  307 |  default:
      |  ^~~~~~~
/home/vadimatorik/Downloads/rtl8723du/core/rtw_mlme_ext.c: In function ‘mgt_dispatcher’:
/home/vadimatorik/Downloads/rtl8723du/core/rtw_mlme_ext.c:1688:17: warning: this statement may fall through [-Wimplicit-fallthrough=]
 1688 |    ptable->func = &OnAuthClient;
      |    ~~~~~~~~~~~~~^~~~~~~~~~~~~~~
/home/vadimatorik/Downloads/rtl8723du/core/rtw_mlme_ext.c:1690:2: note: here
 1690 |  case WIFI_ASSOCREQ:
      |  ^~~~
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/rtw_mi.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/rtw_wlan_util.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/rtw_vht.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/rtw_pwrctrl.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/rtw_rf.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/rtw_chplan.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/monitor/rtw_radiotap.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/rtw_recv.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/rtw_sta_mgt.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/rtw_ap.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/wds/rtw_wds.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/mesh/rtw_mesh.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/mesh/rtw_mesh_pathtbl.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/mesh/rtw_mesh_hwmp.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/rtw_xmit.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/rtw_p2p.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/rtw_rson.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/rtw_tdls.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/rtw_br_ext.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/rtw_iol.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/rtw_sreset.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/rtw_btcoex_wifionly.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/rtw_btcoex.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/rtw_beamforming.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/rtw_odm.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/rtw_rm.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/rtw_rm_fsm.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/rtw_ft.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/rtw_wnm.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/rtw_mbo.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/rtw_rm_util.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/efuse/rtw_efuse.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/rtw_roch.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/crypto/aes-internal.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/crypto/aes-internal-enc.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/crypto/aes-gcm.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/crypto/aes-ccm.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/crypto/aes-omac1.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/crypto/ccmp.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/crypto/gcmp.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/crypto/aes-siv.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/crypto/aes-ctr.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/crypto/sha256-internal.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/crypto/sha256.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/crypto/sha256-prf.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/crypto/rtw_crypto_wrap.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/core/rtw_swcrypto.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/os_dep/osdep_service.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/os_dep/linux/os_intfs.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/os_dep/linux/usb_intf.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/os_dep/linux/usb_ops_linux.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/os_dep/linux/ioctl_linux.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/os_dep/linux/xmit_linux.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/os_dep/linux/mlme_linux.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/os_dep/linux/recv_linux.o
  CC [M]  /home/vadimatorik/Downloads/rtl8723du/os_dep/linux/ioctl_cfg80211.o
/home/vadimatorik/Downloads/rtl8723du/os_dep/linux/ioctl_cfg80211.c: In function ‘rtw_cfg80211_ch_switch_notify’:
/home/vadimatorik/Downloads/rtl8723du/os_dep/linux/ioctl_cfg80211.c:458:3: error: too many arguments to function ‘cfg80211_ch_switch_started_notify’
  458 |   cfg80211_ch_switch_started_notify(adapter->pnetdev, &chdef, 0, 0, false);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/vadimatorik/Downloads/rtl8723du/include/osdep_service_linux.h:98,
                 from /home/vadimatorik/Downloads/rtl8723du/include/osdep_service.h:54,
                 from /home/vadimatorik/Downloads/rtl8723du/include/drv_types.h:27,
                 from /home/vadimatorik/Downloads/rtl8723du/os_dep/linux/ioctl_cfg80211.c:17:
./include/net/cfg80211.h:7713:6: note: declared here
 7713 | void cfg80211_ch_switch_started_notify(struct net_device *dev,
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/vadimatorik/Downloads/rtl8723du/os_dep/linux/ioctl_cfg80211.c: In function ‘rtw_get_chbwoff_from_cfg80211_chan_def’:
/home/vadimatorik/Downloads/rtl8723du/os_dep/linux/ioctl_cfg80211.c:6735:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
 6735 |   *ht = 0;
      |   ~~~~^~~
/home/vadimatorik/Downloads/rtl8723du/os_dep/linux/ioctl_cfg80211.c:6737:2: note: here
 6737 |  case NL80211_CHAN_WIDTH_20:
      |  ^~~~
make[2]: *** [scripts/Makefile.build:297: /home/vadimatorik/Downloads/rtl8723du/os_dep/linux/ioctl_cfg80211.o] Error 1
make[1]: *** [Makefile:1907: /home/vadimatorik/Downloads/rtl8723du] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.15.0-72-generic'
make: *** [Makefile:2462: modules] Error 2

```

**Comment by Vadimatorik** [comment]
I think that it needs new static if...
```
#if (LINUX_VERSION_CODE >= KERNEL_VERSION(3, 19, 0))
	if (started) {
#if (LINUX_VERSION_CODE >= KERNEL_VERSION(5, 11, 0))
		cfg80211_ch_switch_started_notify(adapter->pnetdev, &chdef, 0, 0, false);
#else
		cfg80211_ch_switch_started_notify(adapter->pnetdev, &chdef, 0);
#endif
```

**Comment by lwfinger** [comment]
I pushed a fix for builds up to v6.4.

Have you tried the repo at https://github.com/lwfinger/rtw88.git? It now supports the 8723DU.

**Comment by Vadimatorik** [comment]
No. I not try to use it. Thank you. I will try it today.

**Comment by Vadimatorik** [comment]
Okey... I have tried...
```
$ make
make -C /lib/modules/5.15.0-72-generic/build M=/home/vadimatorik/Downloads/rtw88 modules
make[1]: Entering directory '/usr/src/linux-headers-5.15.0-72-generic'
  CC [M]  /home/vadimatorik/Downloads/rtw88/main.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/mac80211.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/util.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/debug.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/tx.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/rx.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/mac.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/phy.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/coex.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/efuse.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/fw.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/ps.o
/home/vadimatorik/Downloads/rtw88/ps.c: In function ‘rtw_recalc_lps’:
/home/vadimatorik/Downloads/rtw88/ps.c:338:39: error: ‘struct ieee80211_vif’ has no member named ‘cfg’
  338 |  if (data.count == 1 && data.found_vif->cfg.ps) {
      |                                       ^~
make[2]: *** [scripts/Makefile.build:297: /home/vadimatorik/Downloads/rtw88/ps.o] Error 1
make[1]: *** [Makefile:1907: /home/vadimatorik/Downloads/rtw88] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.15.0-72-generic'
make: *** [Makefile:117: all] Error 2

```

**Comment by Vadimatorik** [comment]
I cannot build it :(

**Comment by lwfinger** [comment]
I just pushed a fix that should allow a build on kernel 5.15.

**Comment by Vadimatorik** [comment]
> I just pushed a fix that should allow a build on kernel 5.15.

No. It is not working :(

```
$ make
make -C /lib/modules/5.15.0-72-generic/build M=/home/vadimatorik/Downloads/rtw88 modules
make[1]: Entering directory '/usr/src/linux-headers-5.15.0-72-generic'
  CC [M]  /home/vadimatorik/Downloads/rtw88/main.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/mac80211.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/util.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/debug.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/tx.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/rx.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/mac.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/phy.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/coex.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/efuse.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/fw.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/ps.o
/home/vadimatorik/Downloads/rtw88/ps.c: In function ‘rtw_recalc_lps’:
/home/vadimatorik/Downloads/rtw88/ps.c:338:39: error: ‘struct ieee80211_vif’ has no member named ‘cfg’
  338 |  if (data.count == 1 && data.found_vif->cfg.ps) {
      |                                       ^~
make[2]: *** [scripts/Makefile.build:297: /home/vadimatorik/Downloads/rtw88/ps.o] Error 1
make[1]: *** [Makefile:1907: /home/vadimatorik/Downloads/rtw88] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.15.0-72-generic'
make: *** [Makefile:117: all] Error 2
```
I checked commit version.
```
$ git log
commit e8b743f3d2af2f32eb0825177b746ce5134af56b (HEAD -> master, origin/master, origin/HEAD)
Author: Larry Finger <Larry.Finger@lwfinger.net>
Date:   Sat May 27 09:56:16 2023 -0500

    Revert "rtw88: Disable SUPPORTS_DYNAMIC_PS"
    
    This reverts commit 4cbee7154f9223d536ad745d2222dae8ad6d8e17.
```

**Comment by lwfinger** [comment]
I just pushed a fix that should take care of your problem.

**Comment by Vadimatorik** [comment]
> I just pushed a fix that should take care of your problem.

Thank you) I did it.

```
$ make 
make -C /lib/modules/5.15.0-72-generic/build M=/home/vadimatorik/Downloads/rtw88 modules
make[1]: Entering directory '/usr/src/linux-headers-5.15.0-72-generic'
  CC [M]  /home/vadimatorik/Downloads/rtw88/main.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/mac80211.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/util.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/debug.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/tx.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/rx.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/mac.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/phy.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/coex.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/efuse.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/fw.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/ps.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/sec.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/wow.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/bf.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/regd.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/sar.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_core.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/rtw8822b.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/rtw8822b_table.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_8822b.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/rtw8822be.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_8822be.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/rtw8822bu.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_8822bu.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/rtw8822bs.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_8822bs.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/rtw8822c.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/rtw8822c_table.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_8822c.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/rtw8822ce.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_8822ce.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/rtw8822cu.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_8822cu.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/rtw8822cs.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_8822cs.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/rtw8723d.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/rtw8723d_table.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_8723d.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/rtw8723de.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_8723de.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/rtw8723du.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_8723du.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/rtw8723ds.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_8723ds.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/rtw8821c.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/rtw8821c_table.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_8821c.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/rtw8821ce.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_8821ce.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_8821cs.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/rtw8821cu.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_8821cu.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/pci.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_pci.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/sdio.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_sdio.o
  CC [M]  /home/vadimatorik/Downloads/rtw88/usb.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_usb.o
  MODPOST /home/vadimatorik/Downloads/rtw88/Module.symvers
  CC [M]  /home/vadimatorik/Downloads/rtw88/rtw_8723d.mod.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_8723d.ko
  BTF [M] /home/vadimatorik/Downloads/rtw88/rtw_8723d.ko
Skipping BTF generation for /home/vadimatorik/Downloads/rtw88/rtw_8723d.ko due to unavailability of vmlinux
  CC [M]  /home/vadimatorik/Downloads/rtw88/rtw_8723de.mod.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_8723de.ko
  BTF [M] /home/vadimatorik/Downloads/rtw88/rtw_8723de.ko
Skipping BTF generation for /home/vadimatorik/Downloads/rtw88/rtw_8723de.ko due to unavailability of vmlinux
  CC [M]  /home/vadimatorik/Downloads/rtw88/rtw_8723ds.mod.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_8723ds.ko
  BTF [M] /home/vadimatorik/Downloads/rtw88/rtw_8723ds.ko
Skipping BTF generation for /home/vadimatorik/Downloads/rtw88/rtw_8723ds.ko due to unavailability of vmlinux
  CC [M]  /home/vadimatorik/Downloads/rtw88/rtw_8723du.mod.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_8723du.ko
  BTF [M] /home/vadimatorik/Downloads/rtw88/rtw_8723du.ko
Skipping BTF generation for /home/vadimatorik/Downloads/rtw88/rtw_8723du.ko due to unavailability of vmlinux
  CC [M]  /home/vadimatorik/Downloads/rtw88/rtw_8821c.mod.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_8821c.ko
  BTF [M] /home/vadimatorik/Downloads/rtw88/rtw_8821c.ko
Skipping BTF generation for /home/vadimatorik/Downloads/rtw88/rtw_8821c.ko due to unavailability of vmlinux
  CC [M]  /home/vadimatorik/Downloads/rtw88/rtw_8821ce.mod.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_8821ce.ko
  BTF [M] /home/vadimatorik/Downloads/rtw88/rtw_8821ce.ko
Skipping BTF generation for /home/vadimatorik/Downloads/rtw88/rtw_8821ce.ko due to unavailability of vmlinux
  CC [M]  /home/vadimatorik/Downloads/rtw88/rtw_8821cs.mod.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_8821cs.ko
  BTF [M] /home/vadimatorik/Downloads/rtw88/rtw_8821cs.ko
Skipping BTF generation for /home/vadimatorik/Downloads/rtw88/rtw_8821cs.ko due to unavailability of vmlinux
  CC [M]  /home/vadimatorik/Downloads/rtw88/rtw_8821cu.mod.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_8821cu.ko
  BTF [M] /home/vadimatorik/Downloads/rtw88/rtw_8821cu.ko
Skipping BTF generation for /home/vadimatorik/Downloads/rtw88/rtw_8821cu.ko due to unavailability of vmlinux
  CC [M]  /home/vadimatorik/Downloads/rtw88/rtw_8822b.mod.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_8822b.ko
  BTF [M] /home/vadimatorik/Downloads/rtw88/rtw_8822b.ko
Skipping BTF generation for /home/vadimatorik/Downloads/rtw88/rtw_8822b.ko due to unavailability of vmlinux
  CC [M]  /home/vadimatorik/Downloads/rtw88/rtw_8822be.mod.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_8822be.ko
  BTF [M] /home/vadimatorik/Downloads/rtw88/rtw_8822be.ko
Skipping BTF generation for /home/vadimatorik/Downloads/rtw88/rtw_8822be.ko due to unavailability of vmlinux
  CC [M]  /home/vadimatorik/Downloads/rtw88/rtw_8822bs.mod.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_8822bs.ko
  BTF [M] /home/vadimatorik/Downloads/rtw88/rtw_8822bs.ko
Skipping BTF generation for /home/vadimatorik/Downloads/rtw88/rtw_8822bs.ko due to unavailability of vmlinux
  CC [M]  /home/vadimatorik/Downloads/rtw88/rtw_8822bu.mod.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_8822bu.ko
  BTF [M] /home/vadimatorik/Downloads/rtw88/rtw_8822bu.ko
Skipping BTF generation for /home/vadimatorik/Downloads/rtw88/rtw_8822bu.ko due to unavailability of vmlinux
  CC [M]  /home/vadimatorik/Downloads/rtw88/rtw_8822c.mod.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_8822c.ko
  BTF [M] /home/vadimatorik/Downloads/rtw88/rtw_8822c.ko
Skipping BTF generation for /home/vadimatorik/Downloads/rtw88/rtw_8822c.ko due to unavailability of vmlinux
  CC [M]  /home/vadimatorik/Downloads/rtw88/rtw_8822ce.mod.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_8822ce.ko
  BTF [M] /home/vadimatorik/Downloads/rtw88/rtw_8822ce.ko
Skipping BTF generation for /home/vadimatorik/Downloads/rtw88/rtw_8822ce.ko due to unavailability of vmlinux
  CC [M]  /home/vadimatorik/Downloads/rtw88/rtw_8822cs.mod.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_8822cs.ko
  BTF [M] /home/vadimatorik/Downloads/rtw88/rtw_8822cs.ko
Skipping BTF generation for /home/vadimatorik/Downloads/rtw88/rtw_8822cs.ko due to unavailability of vmlinux
  CC [M]  /home/vadimatorik/Downloads/rtw88/rtw_8822cu.mod.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_8822cu.ko
  BTF [M] /home/vadimatorik/Downloads/rtw88/rtw_8822cu.ko
Skipping BTF generation for /home/vadimatorik/Downloads/rtw88/rtw_8822cu.ko due to unavailability of vmlinux
  CC [M]  /home/vadimatorik/Downloads/rtw88/rtw_core.mod.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_core.ko
  BTF [M] /home/vadimatorik/Downloads/rtw88/rtw_core.ko
Skipping BTF generation for /home/vadimatorik/Downloads/rtw88/rtw_core.ko due to unavailability of vmlinux
  CC [M]  /home/vadimatorik/Downloads/rtw88/rtw_pci.mod.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_pci.ko
  BTF [M] /home/vadimatorik/Downloads/rtw88/rtw_pci.ko
Skipping BTF generation for /home/vadimatorik/Downloads/rtw88/rtw_pci.ko due to unavailability of vmlinux
  CC [M]  /home/vadimatorik/Downloads/rtw88/rtw_sdio.mod.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_sdio.ko
  BTF [M] /home/vadimatorik/Downloads/rtw88/rtw_sdio.ko
Skipping BTF generation for /home/vadimatorik/Downloads/rtw88/rtw_sdio.ko due to unavailability of vmlinux
  CC [M]  /home/vadimatorik/Downloads/rtw88/rtw_usb.mod.o
  LD [M]  /home/vadimatorik/Downloads/rtw88/rtw_usb.ko
  BTF [M] /home/vadimatorik/Downloads/rtw88/rtw_usb.ko
Skipping BTF generation for /home/vadimatorik/Downloads/rtw88/rtw_usb.ko due to unavailability of vmlinux
make[1]: Leaving directory '/usr/src/linux-headers-5.15.0-72-generic'
```

**Comment by Vadimatorik** [comment]
But I cannot turn on it:
```
$ sudo make install
make -C /lib/modules/5.15.0-72-generic/build M=/home/vadimatorik/Downloads/rtw88 modules
make[1]: Entering directory '/usr/src/linux-headers-5.15.0-72-generic'
make[1]: Leaving directory '/usr/src/linux-headers-5.15.0-72-generic'
Install rtw88 SUCCESS

$ sudo modprobe -v 8723du 
modprobe: FATAL: Module 8723du not found in directory /lib/modules/5.15.0-72-generic

```

**Comment by lwfinger** [comment]
The module is named rtw_8723du, not 8723du.

**Comment by Vadimatorik** [comment]
I'm sorry))) Okey) It's working) Thank you very math)
